/*
 * Monty Relais Colis Parcel Shop Connector
 * This connector can retrieve parcel shop information for Relais Colis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.parcel_shop.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Represents the available carrier (value: RELAIS_COLIS). 
 */
public enum Carrier {
  
  COLIS("RELAIS_COLIS");

  private String value;

  Carrier(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Carrier fromValue(String text) {
    for (Carrier b : Carrier.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

