/*
 * Monty Relais Colis Parcel Shop Connector
 * This connector can retrieve parcel shop information for Relais Colis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.parcel_shop.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * An error thrown by the API
 */
@ApiModel(description = "An error thrown by the API")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-06T15:12:17.756+01:00")
public class ErrorInfo {
  @JsonProperty("timestamp")
  private String timestamp = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("error")
  private String error = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("path")
  private String path = null;

  @JsonProperty("errors")
  private List<ErrorDetail> errors = null;

  public ErrorInfo timestamp(String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * The date-time when the error occurred
   * @return timestamp
  **/
  @ApiModelProperty(value = "The date-time when the error occurred")
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public ErrorInfo status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * The status code of the error
   * @return status
  **/
  @ApiModelProperty(value = "The status code of the error")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public ErrorInfo error(String error) {
    this.error = error;
    return this;
  }

   /**
   * The type of the error
   * @return error
  **/
  @ApiModelProperty(value = "The type of the error")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public ErrorInfo message(String message) {
    this.message = message;
    return this;
  }

   /**
   * A message describing the error
   * @return message
  **/
  @ApiModelProperty(value = "A message describing the error")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ErrorInfo path(String path) {
    this.path = path;
    return this;
  }

   /**
   * The URL path where the error occurred
   * @return path
  **/
  @ApiModelProperty(value = "The URL path where the error occurred")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public ErrorInfo errors(List<ErrorDetail> errors) {
    this.errors = errors;
    return this;
  }

  public ErrorInfo addErrorsItem(ErrorDetail errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<ErrorDetail>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * A collection of details about the errors
   * @return errors
  **/
  @ApiModelProperty(value = "A collection of details about the errors")
  public List<ErrorDetail> getErrors() {
    return errors;
  }

  public void setErrors(List<ErrorDetail> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorInfo errorInfo = (ErrorInfo) o;
    return Objects.equals(this.timestamp, errorInfo.timestamp) &&
        Objects.equals(this.status, errorInfo.status) &&
        Objects.equals(this.error, errorInfo.error) &&
        Objects.equals(this.message, errorInfo.message) &&
        Objects.equals(this.path, errorInfo.path) &&
        Objects.equals(this.errors, errorInfo.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, status, error, message, path, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorInfo {\n");
    
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

