/*
 * Monty Relais Colis Parcel Shop Connector
 * This connector can retrieve parcel shop information for Relais Colis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.parcel_shop.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Details about an error, usually specific to a field.
 */
@ApiModel(description = "Details about an error, usually specific to a field.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-06T15:12:17.756+01:00")
public class ErrorDetail {
  @JsonProperty("code")
  private String code = null;

  @JsonProperty("defaultMessage")
  private String defaultMessage = null;

  @JsonProperty("objectName")
  private String objectName = null;

  @JsonProperty("field")
  private String field = null;

  public ErrorDetail code(String code) {
    this.code = code;
    return this;
  }

   /**
   * A code for the specific error
   * @return code
  **/
  @ApiModelProperty(value = "A code for the specific error")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ErrorDetail defaultMessage(String defaultMessage) {
    this.defaultMessage = defaultMessage;
    return this;
  }

   /**
   * A detailed error message
   * @return defaultMessage
  **/
  @ApiModelProperty(value = "A detailed error message")
  public String getDefaultMessage() {
    return defaultMessage;
  }

  public void setDefaultMessage(String defaultMessage) {
    this.defaultMessage = defaultMessage;
  }

  public ErrorDetail objectName(String objectName) {
    this.objectName = objectName;
    return this;
  }

   /**
   * The name of the object that caused the error
   * @return objectName
  **/
  @ApiModelProperty(value = "The name of the object that caused the error")
  public String getObjectName() {
    return objectName;
  }

  public void setObjectName(String objectName) {
    this.objectName = objectName;
  }

  public ErrorDetail field(String field) {
    this.field = field;
    return this;
  }

   /**
   * The name of the field that caused the error
   * @return field
  **/
  @ApiModelProperty(value = "The name of the field that caused the error")
  public String getField() {
    return field;
  }

  public void setField(String field) {
    this.field = field;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorDetail errorDetail = (ErrorDetail) o;
    return Objects.equals(this.code, errorDetail.code) &&
        Objects.equals(this.defaultMessage, errorDetail.defaultMessage) &&
        Objects.equals(this.objectName, errorDetail.objectName) &&
        Objects.equals(this.field, errorDetail.field);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, defaultMessage, objectName, field);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorDetail {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    defaultMessage: ").append(toIndentedString(defaultMessage)).append("\n");
    sb.append("    objectName: ").append(toIndentedString(objectName)).append("\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

