/*
 * Monty Relais Colis Parcel Shop Connector
 * This connector can retrieve parcel shop information for Relais Colis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.parcel_shop.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * OpeningTime
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-06T15:12:17.756+01:00")
public class OpeningTime {
  @JsonProperty("day")
  private Integer day = null;

  @JsonProperty("from")
  private String from = null;

  @JsonProperty("to")
  private String to = null;

  @JsonProperty("closedDuring")
  private String closedDuring = null;

  public OpeningTime day(Integer day) {
    this.day = day;
    return this;
  }

   /**
   * The one-based weekday number the opening times are valid for. Week starting day is Monday.
   * @return day
  **/
  @ApiModelProperty(value = "The one-based weekday number the opening times are valid for. Week starting day is Monday.")
  public Integer getDay() {
    return day;
  }

  public void setDay(Integer day) {
    this.day = day;
  }

  public OpeningTime from(String from) {
    this.from = from;
    return this;
  }

   /**
   * The opening time (e.g. \&quot;09:00\&quot;)
   * @return from
  **/
  @ApiModelProperty(value = "The opening time (e.g. \"09:00\")")
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

  public OpeningTime to(String to) {
    this.to = to;
    return this;
  }

   /**
   * The closing time (e.g. \&quot;17:00\&quot;)
   * @return to
  **/
  @ApiModelProperty(value = "The closing time (e.g. \"17:00\")")
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }

  public OpeningTime closedDuring(String closedDuring) {
    this.closedDuring = closedDuring;
    return this;
  }

   /**
   * Closes during the given time (e.g. \&quot;12:00-14:00\&quot;)
   * @return closedDuring
  **/
  @ApiModelProperty(value = "Closes during the given time (e.g. \"12:00-14:00\")")
  public String getClosedDuring() {
    return closedDuring;
  }

  public void setClosedDuring(String closedDuring) {
    this.closedDuring = closedDuring;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpeningTime openingTime = (OpeningTime) o;
    return Objects.equals(this.day, openingTime.day) &&
        Objects.equals(this.from, openingTime.from) &&
        Objects.equals(this.to, openingTime.to) &&
        Objects.equals(this.closedDuring, openingTime.closedDuring);
  }

  @Override
  public int hashCode() {
    return Objects.hash(day, from, to, closedDuring);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpeningTime {\n");
    
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    closedDuring: ").append(toIndentedString(closedDuring)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

