/*
 * Monty Relais Colis Parcel Shop Connector
 * This connector can retrieve parcel shop information for Relais Colis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.parcel_shop.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * A Parcel shop
 */
@ApiModel(description = "A Parcel shop")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-06T15:12:17.756+01:00")
public class ParcelShop {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("latitude")
  private Double latitude = null;

  @JsonProperty("longitude")
  private Double longitude = null;

  @JsonProperty("carrier")
  private Carrier carrier = null;

  @JsonProperty("addressLine1")
  private String addressLine1 = null;

  @JsonProperty("postCode")
  private String postCode = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("openingTimes")
  private List<OpeningTime> openingTimes = null;

  @JsonProperty("carrierData")
  private String carrierData = null;

  public ParcelShop id(String id) {
    this.id = id;
    return this;
  }

   /**
   * the id of the parcel shop used
   * @return id
  **/
  @ApiModelProperty(value = "the id of the parcel shop used")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ParcelShop name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the parcel shop
   * @return name
  **/
  @ApiModelProperty(value = "The name of the parcel shop")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ParcelShop type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of the parcel shop, the value is dependant on the carrier. If the carrier has only one type of parcel shop this value will be filled with the value &#39;parcelshop&#39; 
   * @return type
  **/
  @ApiModelProperty(value = "The type of the parcel shop, the value is dependant on the carrier. If the carrier has only one type of parcel shop this value will be filled with the value 'parcelshop' ")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ParcelShop latitude(Double latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * The latitude of the parcel shop
   * @return latitude
  **/
  @ApiModelProperty(value = "The latitude of the parcel shop")
  public Double getLatitude() {
    return latitude;
  }

  public void setLatitude(Double latitude) {
    this.latitude = latitude;
  }

  public ParcelShop longitude(Double longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * The longitude of the parcel shop
   * @return longitude
  **/
  @ApiModelProperty(value = "The longitude of the parcel shop")
  public Double getLongitude() {
    return longitude;
  }

  public void setLongitude(Double longitude) {
    this.longitude = longitude;
  }

  public ParcelShop carrier(Carrier carrier) {
    this.carrier = carrier;
    return this;
  }

   /**
   * The carrier that is serviced through this parcel shop
   * @return carrier
  **/
  @ApiModelProperty(value = "The carrier that is serviced through this parcel shop")
  public Carrier getCarrier() {
    return carrier;
  }

  public void setCarrier(Carrier carrier) {
    this.carrier = carrier;
  }

  public ParcelShop addressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
    return this;
  }

   /**
   * the address of the parcel shop
   * @return addressLine1
  **/
  @ApiModelProperty(value = "the address of the parcel shop")
  public String getAddressLine1() {
    return addressLine1;
  }

  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }

  public ParcelShop postCode(String postCode) {
    this.postCode = postCode;
    return this;
  }

   /**
   * The post code of the parcel shop.
   * @return postCode
  **/
  @ApiModelProperty(value = "The post code of the parcel shop.")
  public String getPostCode() {
    return postCode;
  }

  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }

  public ParcelShop city(String city) {
    this.city = city;
    return this;
  }

   /**
   * The city the parcel shop is located in.
   * @return city
  **/
  @ApiModelProperty(value = "The city the parcel shop is located in.")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public ParcelShop country(String country) {
    this.country = country;
    return this;
  }

   /**
   * The country the parcel shop is located in.
   * @return country
  **/
  @ApiModelProperty(value = "The country the parcel shop is located in.")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public ParcelShop openingTimes(List<OpeningTime> openingTimes) {
    this.openingTimes = openingTimes;
    return this;
  }

  public ParcelShop addOpeningTimesItem(OpeningTime openingTimesItem) {
    if (this.openingTimes == null) {
      this.openingTimes = new ArrayList<OpeningTime>();
    }
    this.openingTimes.add(openingTimesItem);
    return this;
  }

   /**
   * A list containing the opening times of the parcel shop.
   * @return openingTimes
  **/
  @ApiModelProperty(value = "A list containing the opening times of the parcel shop.")
  public List<OpeningTime> getOpeningTimes() {
    return openingTimes;
  }

  public void setOpeningTimes(List<OpeningTime> openingTimes) {
    this.openingTimes = openingTimes;
  }

  public ParcelShop carrierData(String carrierData) {
    this.carrierData = carrierData;
    return this;
  }

   /**
   * Custom data from the carrier, the data is in JSON format and differs per carrier. Not all carriers have extra data that is returned. 
   * @return carrierData
  **/
  @ApiModelProperty(value = "Custom data from the carrier, the data is in JSON format and differs per carrier. Not all carriers have extra data that is returned. ")
  public String getCarrierData() {
    return carrierData;
  }

  public void setCarrierData(String carrierData) {
    this.carrierData = carrierData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParcelShop parcelShop = (ParcelShop) o;
    return Objects.equals(this.id, parcelShop.id) &&
        Objects.equals(this.name, parcelShop.name) &&
        Objects.equals(this.type, parcelShop.type) &&
        Objects.equals(this.latitude, parcelShop.latitude) &&
        Objects.equals(this.longitude, parcelShop.longitude) &&
        Objects.equals(this.carrier, parcelShop.carrier) &&
        Objects.equals(this.addressLine1, parcelShop.addressLine1) &&
        Objects.equals(this.postCode, parcelShop.postCode) &&
        Objects.equals(this.city, parcelShop.city) &&
        Objects.equals(this.country, parcelShop.country) &&
        Objects.equals(this.openingTimes, parcelShop.openingTimes) &&
        Objects.equals(this.carrierData, parcelShop.carrierData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, type, latitude, longitude, carrier, addressLine1, postCode, city, country, openingTimes, carrierData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParcelShop {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    postCode: ").append(toIndentedString(postCode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    openingTimes: ").append(toIndentedString(openingTimes)).append("\n");
    sb.append("    carrierData: ").append(toIndentedString(carrierData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

