/*
 * Monty Authentication API
 * Authentication service for the Monty API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.auth.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A request to authorize a user against a client with a specific permission
 */
@ApiModel(description = "A request to authorize a user against a client with a specific permission")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-06T14:03:51.433+01:00")
public class AuthorizationRequest {
  @JsonProperty("token")
  private String token = null;

  @JsonProperty("clientId")
  private Long clientId = null;

  @JsonProperty("permission")
  private String permission = null;

  public AuthorizationRequest token(String token) {
    this.token = token;
    return this;
  }

   /**
   * The token that identifies the user
   * @return token
  **/
  @ApiModelProperty(required = true, value = "The token that identifies the user")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public AuthorizationRequest clientId(Long clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * The client ID
   * minimum: 1
   * @return clientId
  **/
  @ApiModelProperty(required = true, value = "The client ID")
  public Long getClientId() {
    return clientId;
  }

  public void setClientId(Long clientId) {
    this.clientId = clientId;
  }

  public AuthorizationRequest permission(String permission) {
    this.permission = permission;
    return this;
  }

   /**
   * An optional permission to check. If not provided, any access is enough.
   * @return permission
  **/
  @ApiModelProperty(value = "An optional permission to check. If not provided, any access is enough.")
  public String getPermission() {
    return permission;
  }

  public void setPermission(String permission) {
    this.permission = permission;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizationRequest authorizationRequest = (AuthorizationRequest) o;
    return Objects.equals(this.token, authorizationRequest.token) &&
        Objects.equals(this.clientId, authorizationRequest.clientId) &&
        Objects.equals(this.permission, authorizationRequest.permission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, clientId, permission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizationRequest {\n");
    
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

