/*
 * Monty Authentication API
 * Authentication service for the Monty API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.auth.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The request for changing the password 
 */
@ApiModel(description = "The request for changing the password ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-06T14:03:51.433+01:00")
public class ConfirmForgotPasswordRequest {
  @JsonProperty("password")
  private String password = null;

  @JsonProperty("confirmationCode")
  private String confirmationCode = null;

  public ConfirmForgotPasswordRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * The new user&#39;s password
   * @return password
  **/
  @ApiModelProperty(value = "The new user's password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public ConfirmForgotPasswordRequest confirmationCode(String confirmationCode) {
    this.confirmationCode = confirmationCode;
    return this;
  }

   /**
   * The confirmation code sent by a user&#39;s request to retrieve a forgotten password.
   * @return confirmationCode
  **/
  @ApiModelProperty(value = "The confirmation code sent by a user's request to retrieve a forgotten password.")
  public String getConfirmationCode() {
    return confirmationCode;
  }

  public void setConfirmationCode(String confirmationCode) {
    this.confirmationCode = confirmationCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfirmForgotPasswordRequest confirmForgotPasswordRequest = (ConfirmForgotPasswordRequest) o;
    return Objects.equals(this.password, confirmForgotPasswordRequest.password) &&
        Objects.equals(this.confirmationCode, confirmForgotPasswordRequest.confirmationCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(password, confirmationCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfirmForgotPasswordRequest {\n");
    
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    confirmationCode: ").append(toIndentedString(confirmationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

