/*
 * Monty Authentication API
 * Authentication service for the Monty API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.auth.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Contant information
 */
@ApiModel(description = "Contant information")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-06T14:03:51.433+01:00")
public class ContactInfo {
  @JsonProperty("dialCode")
  private String dialCode = null;

  @JsonProperty("telephone")
  private String telephone = null;

  @JsonProperty("email")
  private String email = null;

  public ContactInfo dialCode(String dialCode) {
    this.dialCode = dialCode;
    return this;
  }

   /**
   * Area code or dial code
   * @return dialCode
  **/
  @ApiModelProperty(required = true, value = "Area code or dial code")
  public String getDialCode() {
    return dialCode;
  }

  public void setDialCode(String dialCode) {
    this.dialCode = dialCode;
  }

  public ContactInfo telephone(String telephone) {
    this.telephone = telephone;
    return this;
  }

   /**
   * The telephone number
   * @return telephone
  **/
  @ApiModelProperty(required = true, value = "The telephone number")
  public String getTelephone() {
    return telephone;
  }

  public void setTelephone(String telephone) {
    this.telephone = telephone;
  }

  public ContactInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * E-mail address for contacting
   * @return email
  **/
  @ApiModelProperty(required = true, value = "E-mail address for contacting")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactInfo contactInfo = (ContactInfo) o;
    return Objects.equals(this.dialCode, contactInfo.dialCode) &&
        Objects.equals(this.telephone, contactInfo.telephone) &&
        Objects.equals(this.email, contactInfo.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dialCode, telephone, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactInfo {\n");
    
    sb.append("    dialCode: ").append(toIndentedString(dialCode)).append("\n");
    sb.append("    telephone: ").append(toIndentedString(telephone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

