/*
 * Monty Authentication API
 * Authentication service for the Monty API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.auth.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Represents an external user.
 */
@ApiModel(description = "Represents an external user.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-06T14:03:51.433+01:00")
public class ExternalUser {
  @JsonProperty("externalOrigin")
  private String externalOrigin = null;

  @JsonProperty("externalId")
  private String externalId = null;

  @JsonProperty("externalClientId")
  private String externalClientId = null;

  @JsonProperty("externalClientOrigin")
  private String externalClientOrigin = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("username")
  private String username = null;

  @JsonProperty("email")
  private String email = null;

  public ExternalUser externalOrigin(String externalOrigin) {
    this.externalOrigin = externalOrigin;
    return this;
  }

   /**
   * The external origin identifies the owner of the user.
   * @return externalOrigin
  **/
  @ApiModelProperty(required = true, value = "The external origin identifies the owner of the user.")
  public String getExternalOrigin() {
    return externalOrigin;
  }

  public void setExternalOrigin(String externalOrigin) {
    this.externalOrigin = externalOrigin;
  }

  public ExternalUser externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * The unique identifier of the user in the system it originated from.
   * @return externalId
  **/
  @ApiModelProperty(required = true, value = "The unique identifier of the user in the system it originated from.")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public ExternalUser externalClientId(String externalClientId) {
    this.externalClientId = externalClientId;
    return this;
  }

   /**
   * The unique identifier of the client who owns this user in the system it originated from.
   * @return externalClientId
  **/
  @ApiModelProperty(required = true, value = "The unique identifier of the client who owns this user in the system it originated from.")
  public String getExternalClientId() {
    return externalClientId;
  }

  public void setExternalClientId(String externalClientId) {
    this.externalClientId = externalClientId;
  }

  public ExternalUser externalClientOrigin(String externalClientOrigin) {
    this.externalClientOrigin = externalClientOrigin;
    return this;
  }

   /**
   * The external client origin identifies the owner of the client.
   * @return externalClientOrigin
  **/
  @ApiModelProperty(required = true, value = "The external client origin identifies the owner of the client.")
  public String getExternalClientOrigin() {
    return externalClientOrigin;
  }

  public void setExternalClientOrigin(String externalClientOrigin) {
    this.externalClientOrigin = externalClientOrigin;
  }

  public ExternalUser firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * The first name of the user.
   * @return firstName
  **/
  @ApiModelProperty(required = true, value = "The first name of the user.")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ExternalUser lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * The last name of the user.
   * @return lastName
  **/
  @ApiModelProperty(required = true, value = "The last name of the user.")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public ExternalUser username(String username) {
    this.username = username;
    return this;
  }

   /**
   * The username of the user.
   * @return username
  **/
  @ApiModelProperty(required = true, value = "The username of the user.")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public ExternalUser email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email of the user.
   * @return email
  **/
  @ApiModelProperty(required = true, value = "The email of the user.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalUser externalUser = (ExternalUser) o;
    return Objects.equals(this.externalOrigin, externalUser.externalOrigin) &&
        Objects.equals(this.externalId, externalUser.externalId) &&
        Objects.equals(this.externalClientId, externalUser.externalClientId) &&
        Objects.equals(this.externalClientOrigin, externalUser.externalClientOrigin) &&
        Objects.equals(this.firstName, externalUser.firstName) &&
        Objects.equals(this.lastName, externalUser.lastName) &&
        Objects.equals(this.username, externalUser.username) &&
        Objects.equals(this.email, externalUser.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalOrigin, externalId, externalClientId, externalClientOrigin, firstName, lastName, username, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalUser {\n");
    
    sb.append("    externalOrigin: ").append(toIndentedString(externalOrigin)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    externalClientId: ").append(toIndentedString(externalClientId)).append("\n");
    sb.append("    externalClientOrigin: ").append(toIndentedString(externalClientOrigin)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

