/*
 * Monty Authentication API
 * Authentication service for the Monty API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.auth.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * A request to invite a new user. Used by an administrator to invite new users.
 */
@ApiModel(description = "A request to invite a new user. Used by an administrator to invite new users.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-06T14:03:51.433+01:00")
public class InviteUserRequest {
  @JsonProperty("email")
  private String email = null;

  @JsonProperty("roleIds")
  private List<Long> roleIds = new ArrayList<Long>();

  public InviteUserRequest email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The email of the user.
   * @return email
  **/
  @ApiModelProperty(required = true, value = "The email of the user.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public InviteUserRequest roleIds(List<Long> roleIds) {
    this.roleIds = roleIds;
    return this;
  }

  public InviteUserRequest addRoleIdsItem(Long roleIdsItem) {
    this.roleIds.add(roleIdsItem);
    return this;
  }

   /**
   * List of role ids that the user should be assigned to within the client.
   * @return roleIds
  **/
  @ApiModelProperty(required = true, value = "List of role ids that the user should be assigned to within the client.")
  public List<Long> getRoleIds() {
    return roleIds;
  }

  public void setRoleIds(List<Long> roleIds) {
    this.roleIds = roleIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InviteUserRequest inviteUserRequest = (InviteUserRequest) o;
    return Objects.equals(this.email, inviteUserRequest.email) &&
        Objects.equals(this.roleIds, inviteUserRequest.roleIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, roleIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InviteUserRequest {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    roleIds: ").append(toIndentedString(roleIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

