/*
 * Monty Authentication API
 * Authentication service for the Monty API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.auth.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * The result of the login operation includes the access token and the user details
 */
@ApiModel(description = "The result of the login operation includes the access token and the user details")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-06T14:03:51.433+01:00")
public class LoginResult {
  @JsonProperty("email")
  private String email = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("newsletterOptIn")
  private Boolean newsletterOptIn = null;

  @JsonProperty("createdAt")
  private DateTime createdAt = null;

  @JsonProperty("username")
  private String username = null;

  @JsonProperty("claims")
  private List<Claim> claims = null;

  @JsonProperty("accessToken")
  private String accessToken = null;

  @JsonProperty("expiresIn")
  private Integer expiresIn = null;

  @JsonProperty("refreshToken")
  private String refreshToken = null;

  public LoginResult email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The e-mail of the user
   * @return email
  **/
  @ApiModelProperty(required = true, value = "The e-mail of the user")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public LoginResult firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * The first name of the user
   * @return firstName
  **/
  @ApiModelProperty(required = true, value = "The first name of the user")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public LoginResult lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * The last name of the user
   * @return lastName
  **/
  @ApiModelProperty(required = true, value = "The last name of the user")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public LoginResult newsletterOptIn(Boolean newsletterOptIn) {
    this.newsletterOptIn = newsletterOptIn;
    return this;
  }

   /**
   * Indicates if the user is subscribed to the newsletter
   * @return newsletterOptIn
  **/
  @ApiModelProperty(value = "Indicates if the user is subscribed to the newsletter")
  public Boolean getNewsletterOptIn() {
    return newsletterOptIn;
  }

  public void setNewsletterOptIn(Boolean newsletterOptIn) {
    this.newsletterOptIn = newsletterOptIn;
  }

  public LoginResult createdAt(DateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The date and time when the user was created
   * @return createdAt
  **/
  @ApiModelProperty(value = "The date and time when the user was created")
  public DateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }

  public LoginResult username(String username) {
    this.username = username;
    return this;
  }

   /**
   * The username of the user
   * @return username
  **/
  @ApiModelProperty(value = "The username of the user")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public LoginResult claims(List<Claim> claims) {
    this.claims = claims;
    return this;
  }

  public LoginResult addClaimsItem(Claim claimsItem) {
    if (this.claims == null) {
      this.claims = new ArrayList<Claim>();
    }
    this.claims.add(claimsItem);
    return this;
  }

   /**
   * The clients that the user is a member of
   * @return claims
  **/
  @ApiModelProperty(value = "The clients that the user is a member of")
  public List<Claim> getClaims() {
    return claims;
  }

  public void setClaims(List<Claim> claims) {
    this.claims = claims;
  }

  public LoginResult accessToken(String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

   /**
   * The access token to use for subsequent requests
   * @return accessToken
  **/
  @ApiModelProperty(value = "The access token to use for subsequent requests")
  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  public LoginResult expiresIn(Integer expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

   /**
   * The period in seconds that the access token is valid for from the moment it was issued
   * @return expiresIn
  **/
  @ApiModelProperty(value = "The period in seconds that the access token is valid for from the moment it was issued")
  public Integer getExpiresIn() {
    return expiresIn;
  }

  public void setExpiresIn(Integer expiresIn) {
    this.expiresIn = expiresIn;
  }

  public LoginResult refreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
    return this;
  }

   /**
   * The refresh token used to refresh the access token
   * @return refreshToken
  **/
  @ApiModelProperty(value = "The refresh token used to refresh the access token")
  public String getRefreshToken() {
    return refreshToken;
  }

  public void setRefreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginResult loginResult = (LoginResult) o;
    return Objects.equals(this.email, loginResult.email) &&
        Objects.equals(this.firstName, loginResult.firstName) &&
        Objects.equals(this.lastName, loginResult.lastName) &&
        Objects.equals(this.newsletterOptIn, loginResult.newsletterOptIn) &&
        Objects.equals(this.createdAt, loginResult.createdAt) &&
        Objects.equals(this.username, loginResult.username) &&
        Objects.equals(this.claims, loginResult.claims) &&
        Objects.equals(this.accessToken, loginResult.accessToken) &&
        Objects.equals(this.expiresIn, loginResult.expiresIn) &&
        Objects.equals(this.refreshToken, loginResult.refreshToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, firstName, lastName, newsletterOptIn, createdAt, username, claims, accessToken, expiresIn, refreshToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginResult {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    newsletterOptIn: ").append(toIndentedString(newsletterOptIn)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    claims: ").append(toIndentedString(claims)).append("\n");
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    refreshToken: ").append(toIndentedString(refreshToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

