/*
 * Monty Authentication API
 * Authentication service for the Monty API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.auth.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The result of the refresh token operation includes the new access token
 */
@ApiModel(description = "The result of the refresh token operation includes the new access token")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-06T14:03:51.433+01:00")
public class RefreshTokenResult {
  @JsonProperty("accessToken")
  private String accessToken = null;

  @JsonProperty("expiresIn")
  private Integer expiresIn = null;

  @JsonProperty("refreshToken")
  private String refreshToken = null;

  public RefreshTokenResult accessToken(String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

   /**
   * The access token to use for subsequent requests
   * @return accessToken
  **/
  @ApiModelProperty(value = "The access token to use for subsequent requests")
  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  public RefreshTokenResult expiresIn(Integer expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

   /**
   * The period in seconds that the access token is valid for from the moment it was issued
   * @return expiresIn
  **/
  @ApiModelProperty(value = "The period in seconds that the access token is valid for from the moment it was issued")
  public Integer getExpiresIn() {
    return expiresIn;
  }

  public void setExpiresIn(Integer expiresIn) {
    this.expiresIn = expiresIn;
  }

  public RefreshTokenResult refreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
    return this;
  }

   /**
   * The refresh token used to refresh the access token
   * @return refreshToken
  **/
  @ApiModelProperty(value = "The refresh token used to refresh the access token")
  public String getRefreshToken() {
    return refreshToken;
  }

  public void setRefreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefreshTokenResult refreshTokenResult = (RefreshTokenResult) o;
    return Objects.equals(this.accessToken, refreshTokenResult.accessToken) &&
        Objects.equals(this.expiresIn, refreshTokenResult.expiresIn) &&
        Objects.equals(this.refreshToken, refreshTokenResult.refreshToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, expiresIn, refreshToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefreshTokenResult {\n");
    
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    refreshToken: ").append(toIndentedString(refreshToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

