/*
 * Monty Authentication API
 * Authentication service for the Monty API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@sendasyou.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ubsend.interview.auth.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a role associated with a claim (e.g. Store Manager). A role belongs to a client. 
 */
@ApiModel(description = "Represents a role associated with a claim (e.g. Store Manager). A role belongs to a client. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-06T14:03:51.433+01:00")
public class Role {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("permissions")
  private List<String> permissions = null;

  @JsonProperty("scope")
  private RoleScope scope = null;

  public Role id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the role.
   * @return id
  **/
  @ApiModelProperty(value = "The ID of the role.")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Role name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the role.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The name of the role.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Role description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The long description of the role
   * @return description
  **/
  @ApiModelProperty(value = "The long description of the role")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Role permissions(List<String> permissions) {
    this.permissions = permissions;
    return this;
  }

  public Role addPermissionsItem(String permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<String>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

   /**
   * The permissions that comprise the role.
   * @return permissions
  **/
  @ApiModelProperty(value = "The permissions that comprise the role.")
  public List<String> getPermissions() {
    return permissions;
  }

  public void setPermissions(List<String> permissions) {
    this.permissions = permissions;
  }

  public Role scope(RoleScope scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Determines the scope of the role. Valid values are LOCAL (the default) and CHILDREN. When set to CHILDREN, the role&#39;s scope extends to the child clients of the client that the role belongs to. 
   * @return scope
  **/
  @ApiModelProperty(value = "Determines the scope of the role. Valid values are LOCAL (the default) and CHILDREN. When set to CHILDREN, the role's scope extends to the child clients of the client that the role belongs to. ")
  public RoleScope getScope() {
    return scope;
  }

  public void setScope(RoleScope scope) {
    this.scope = scope;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Role role = (Role) o;
    return Objects.equals(this.id, role.id) &&
        Objects.equals(this.name, role.name) &&
        Objects.equals(this.description, role.description) &&
        Objects.equals(this.permissions, role.permissions) &&
        Objects.equals(this.scope, role.scope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, permissions, scope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Role {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

